programdir:
  dir: "/projects/wp2/nobackup/Twist_Myeloid/Bin/pomfrey/"

reference:
    ref: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.fasta"
    bwa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta" ##Why two folders should be the same as genome_fasta

bed:
    bedfile: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeloid_v.1.1_padd6_201126.sorted.bed"
    pindel: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/twist_shortlist_pindel-201214.bed"    #annotated_pindel.bed"
    indelartefact: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Artefacts_indels_200602.txt"
    pindelArtefact: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Pindel_artefacts_TM_Nov2020.txt"
    cnvkitartefact: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/CNVkit_artefacts_Nov2022.txt"
    cartool: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeloid_v.1.1_padd6_201126.sorted.bed"
    hotspot: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Hitlist_Sept2016_final_onePOS.bed"
    artefact: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Artefacts_200910.txt"
    germline: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Low_VAF_SNVs_Sept2020.txt"
    intervals: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeloid_v.1.1_padd6_201126.sorted.intervals"
CNV:
    PoN: "/projects/wp4/nobackup/workspace/arielle_test/CNV/officialNormals/TM/readCountPoN_211011.hdf5"
    bedPoN: "/projects/wp4/nobackup/workspace/arielle_test/CNV/bedFiles/TM_TE-annotated_closest-noduplicates.bed"
    interval: "/projects/wp4/nobackup/workspace/arielle_test/CNV/bedFiles/TM_TE-annotated_closest-noduplicates.preprocessed.interval_list"
    cyto: "/projects/wp4/nobackup/workspace/arielle_test/CNV/bin/genomicPos_cytogenCoord.txt"
    cnvkitpool: "/projects/wp2/nobackup/Twist_Myeloid/ReferenceFiles/CNVkit/Reference_Normal_pool.221108.bin267.cnn"

CNA:
    "chr1": "''"
    "chr2": "''"
    "chr3": "''"
    "chr4": "''"
    "chr5": "''"
    "chr6": "''"
    "chr7": "IKZF1"
    "chr8": "''"
    "chr9": "CDKN2A,PAX5"
    "chr10": "''"
    "chr11": "KMT2A"
    "chr12": "BTG1,ETV6"
    "chr13": "RB1"
    "chr14": "''"
    "chr15": "''"
    "chr16": "''"
    "chr17": "TP53"
    "chr18": "''"
    "chr19": "''"
    "chr20": "''"
    "chr21": "RUNX1"
    "chr22": "''"
    "chrX": "CRLF2"
    "chrY": "''"

singularitys:
    cutadapt: "/projects/wp2/nobackup/Twist_Myeloid/Containers/cutadaptv2.5-0.simg"
    bcftools: "docker://hydragenetics/common:0.1.8"
    bedtools: "docker://hydragenetics/common:0.1.8"
    bwa: "docker://hydragenetics/bwa_mem:0.7.17"
    cnvkit: "docker://hydragenetics/cnvkit:0.9.9"
    fastqc: "/projects/wp2/nobackup/Twist_Myeloid/Containers/fastqc0.11.8.simg"
    freebayes: "/projects/wp2/nobackup/Twist_Myeloid/Containers/freebayes-1.3.1-0.simg"
    gatk4: "/projects/wp2/nobackup/Twist_Myeloid/Containers/gatk-4.1.7.0.broad.simg"
    igv: "/projects/wp2/nobackup/Twist_Myeloid/Containers/igv-2.4.10-0.simg"
    mosdepth: "docker://hydragenetics/mosdepth:0.3.2"
    multiqc: "docker://hydragenetics/multiqc:1.11"
    pindel: "docker://hydragenetics/pindel:0.2.5b9"
    pisces: "/projects/wp2/nobackup/Twist_Myeloid/Containers/Pisces-5.2.11.simg"
    python: "/projects/wp2/nobackup/Twist_Myeloid/Containers/python3.9-0.1.0.sif"
    #    python: "/projects/wp2/nobackup/Twist_Myeloid/Containers/python3.6-pysam-xlsxwriter-yaml.simg"
    recall:  "docker://hydragenetics/bcbio-vc:0.2.6" #"/projects/wp4/nobackup/workspace/somatic_dev/singularity/bcbio-variation-recall.simg" #Need one with bcftools and recall
    vardict: "/projects/wp2/nobackup/Twist_Myeloid/Containers/vardict-java-1.7.0-0.simg"
    vep: "/projects/wp2/nobackup/Twist_Myeloid/Containers/ensembl-vep-99.0.simg"
    vt: "/projects/wp2/nobackup/Twist_Myeloid/Containers/vt-0.57721-2.simg"

misc:
    cov_thresholds: "100,200,1000"

methods:
    mutect2: "mutect2"
    vardict: "vardict"
    pisces: "pisces"
    freebayes: "freebayes"

configCache:
    multiqc: "/projects/wp2/nobackup/Twist_Myeloid/Bin/pomfrey/src/report/multiqc_config.yaml"
    igv: "/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/caches/igv/genomes/hg19.genome"
    vep: "/data/ref_genomes/VEP/"
    hemato: "/data/ref_data/COSMIC/COSMIC_v90_hemato_counts.txt"
    variantlist: "/projects/wp2/nobackup/Twist_Myeloid/DetectedVariants/twistVariants-NewDesign2021-10.txt"
