---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/niffler_small_cnv/config/output_files.yaml"

default_container: "docker://hydragenetics/common:0.3.0"

modules:
  alignment: "v0.3.1"
  annotation: "v0.3.0"
  cnv_sv: "v0.4.1"
  compression: "v1.1.0"
  filtering: "v0.1.0"
  misc: "v0.2.0"
  prealignment: "v1.0.0"
  reports: "d8b41c8"
  snv_indels: "v0.3.0"
  qc: "v0.3.0"

reference:
  fasta: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta"
  fai: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.fai"
  design_bed: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/Bedfiles/Probes_merged_ok_Scilifelab_RUNX1-10kb_v2_1X_TE-91815956_hg38.bed"
  design_bed_gz: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/Bedfiles/Probes_merged_ok_Scilifelab_RUNX1-10kb_v2_1X_TE-91815956_hg38.bed.gz"
  design_intervals: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/Bedfiles/Probes_merged_ok_Scilifelab_RUNX1-10kb_v2_1X_TE-91815956_hg38.intervals"
  design_intervals_gatk_cnv: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Workarea/CNVkitNormals/230810/references/preprocess_intervals/Probes_merged_ok_Scilifelab_RUNX1-10kb_v2_1X_TE-91815956_hg38.bed.preprocessed.interval_list" #"/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed.preprocessed.interval_list" CollectReadCounts
  skip_chrs:
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr9"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chr20"
    - "chr22"
    - "chrX"
    - "chrY"
    - "chrM"

trimmer_software: "fastp_pe"

annotate_cnv:
  runx1_exons: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/Bedfiles/RUNX1_NM_001754.5.bed"

bcbio_variation_recall_ensemble:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - gatk_mutect2
    - vardict

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  amb: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.amb"
  ann: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.ann"
  bwt: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.bwt"
  pac: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.pac"
  sa: "/data/ref_genomes/GRCh38/reference_grasnatter/homo_sapiens.fasta.sa"


cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  normal_reference: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Workarea/CNVkitNormals/230810/references/cnvkit_build_normal_reference/cnvkit.PoN.cnn" #230824_100binsize 230810
  method: "hybrid"
  extra: " --drop-low-coverage  " #--segment-method hmm-tumor "

cnvkit_call:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnv_html_report:
  template_dir: /projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/niffler_small_cnv/config/cnv_report_template
  show_table: true

cnvkit_scatter:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  extra: "-c chr21 --y-min -5 --y-max 5"

crumble:
  container: "docker://hydragenetics/crumble:0.9.0"
  extra: "-O CRAM"

export_results_bedtools_intersect:
  extra: " -wb "

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

filter_vcf:
  germline: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/niffler_small_cnv/config/config_germline_filter.yaml"
  snvindels: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/niffler_small_cnv/config/config_snvindels_softfilter.yaml"
  cnv_hardfilter: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/niffler_small_cnv/config/config_cnv_hardfilter.yaml"

gatk_call_copy_ratio_segments:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_collect_allelic_counts:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  SNP_interval: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Workarea/CNVkitNormals/230810/references/preprocess_intervals/Probes_merged_ok_Scilifelab_RUNX1-10kb_v2_1X_TE-91815956_hg38.bed.preprocessed.interval_list" #gnomad eller cnvbackbone

gatk_collect_read_counts:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_denoise_read_counts:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  normal_reference: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Workarea/CNVkitNormals/230810/references/create_read_count_panel_of_normals/gatk_cnv_panel_of_normal.hdf5"

gatk_model_segments:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_mutect2_filter:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_mutect2_merge_stats:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

manta_config_t:
  container: "docker://hydragenetics/manta:1.6.0"
  extra: "--exome"

manta_run_workflow_t:
  container: "docker://hydragenetics/manta:1.6.0"

merge_cnv_json:
  annotations:
    - "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/Bedfiles/RUNX1_NM_001754.5.bed"
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.pathology.svdb_query.annotate_cnv.runx1_exons.filter.cnv_hardfilter.vcf
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.pathology.svdb_query.annotate_cnv.runx1_exons.vcf
  germline_vcf: "snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.vcf"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  thresholds: "100,200,1000"
  
multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    DNA:
      included_unit_types: ['T', 'N']
      config: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/niffler_small_cnv/config/multiqc_config.yaml"
      qc_files:
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.{ext}"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed/{sample}_{type}.per-base.bed.gz"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.global.dist.txt"


picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.4"
  output_ext:
    - "gc_bias.pdf" #collect_gc_bias
    - "gc_bias.summary_metrics"
    - "gc_bias.detail_metrics"
    - "alignment_summary_metrics" # collect_alignment_summary
    - "insert_size_metrics" # collect_insert_size
    - "insert_size_histogram.pdf"
    - "error_summary_metrics" # collect_sequencing_artefact
    - "bait_bias_detail_metrics"
    - "bait_bias_summary_metrics"
    - "pre_adapter_detail_metrics"
    - "pre_adapter_summary_metrics"
    - "quality_distribution_metrics" # quality_score_distribution
    - "quality_distribution.pdf"
    - "quality_yield_metrics" # quality yield metrics

pindel_call:
  include_bed: "/projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Bin/Bedfiles/RUNX1_pindel.bed"
  container: "docker://hydragenetics/pindel:0.2.5b9"

pindel2vcf:
  container: "docker://hydragenetics/pindel:0.2.5b9"
  extra: "-is 5 -he 0.01 -e 10 -mc 10 "

pindel_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

sample_order_multiqc:
  sample_sheet: "SampleSheet.csv"

svdb_merge:
  tc_method:
    - name: pathology
      cnv_caller:
        - cnvkit
        - gatk
  container: "docker://hydragenetics/svdb:2.6.0"

svdb_query:
  container: "docker://hydragenetics/svdb:2.6.0"
  db_string: "--db /projects/wp2/nobackup/CGU_2022_18_RUNX1_CNV/Workarea/CNVkitNormals/230810/references/svdb_export/svdb_cnv.vcf --out_frq Normal_AF --out_occ Normal_OCC"

vardict:
  container: "docker://hydragenetics/vardict:1.8.3"

vep:
  container: "docker://ensemblorg/ensembl-vep:release_110.1" # Ger 110 just nu "docker://hydragenetics/vep:105"
  vep_cache: "/data/ref_genomes/VEP/"
  extra: "--assembly GRCh38 --everything --check_existing --pick --variant_class"

vt_decompose:
  container: "docker://hydragenetics/vt:2015.11.10"

vt_normalize:
  container: "docker://hydragenetics/vt:2015.11.10"
